---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: NFS installation for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - nfs
    - filesystem
    - share
    - nfsv4
    - efs
