---
# tasks file for DNSmasq
#
# 1. Cette tâche permet d'installer DNSmasq
- name: "DNSmasq installation"
  apt:
    name: "dnsmasq"
    state: latest

- name: Create config file for DNSmasq
  template:
   src: "conf.j2"
   dest: "/etc/dnsmasq.conf"

- name: redemarrer le redemarrer
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

-  name: "install tcpdump"
   apt:
     name: tcpdump
     state: present

# - name: "demarrer tcpdump"
#   command: tcpdump etho

# name: "forcer le demarage d'une addresse"
# command: dhclient etho


# 2. Verifions que le DNSmasq est installé et que DHCP est écouté
# - name: "vérification DHCP"
#   command: netstat -anup | grep dhcp
