---

#1. Cette tâche installe le dépôt  EPEL (Extra Packages for Enterprise Linux)
  #- name: "epel activation"
  #  apt:
  #          name: "epel-release"
  #          state: present

#2. Cette tâche installe le dépôt REMI pour bénéficier du paquet PHP7
  #- name: "remi repo activation"
#    apt:
#            name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
#            state: present

#3. Cette tâche installe PHP7 et ses extensions
  - name: "install php70 packages"
    apt:
            name: "php7.3,php-mysql,php-xml,php-gd,php-intl,php-mbstring" #,php-mbstring,php-mcrypt,php-gd,php-intl"
            state: latest
            #enablerepo: "remi-php70"
            #changed_when: yes
    notify: [ "apache restart" ]
